services:

  # NextJS webserver
  apex:
    build:
      context: ./apex
    ports:
      - 5000:5000
    networks:
      - apex

  # LHCI server
  lhci:
    build:
      context: ./lhci
    ports:
      - 9001:9001
    networks:
        - lhci
    volumes:
      - lhci-data:/data

  # NGinx reverse proxy
  nginx:
    image: nginx:alpine

    depends_on:
      - apex
      - lhci

    ports:
      - 443:443
    networks:
      - apex
      - lhci
      - external

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/favicons/:/favicons/:ro

      - /etc/letsencrypt/live/skoh.dev/fullchain.pem:/etc/ssl/skoh-dev/fullchain.pem:ro
      - /etc/letsencrypt/live/skoh.dev/privkey.pem:/etc/ssl/skoh-dev/privkey.pem:ro


networks:
  apex:
    name: apex
    internal: true
  lhci:
    name: lhci
    internal: true
  external:
    name: external


volumes:
  lhci-data:
