services:

  # NextJS webserver
  apex:
    build:
      context: ./apex
    networks:
        - internal

  # Blog
  blog:
    build:
      context: ./blog
    networks:
      - internal
    ports:
      - 8000:80

  # Open WebUI
  openwebui:
    image: ghcr.io/open-webui/open-webui:latest

    networks:
      - external
    volumes:
      - open-webui:/app/backend/data

  # Beszel
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped

    networks:
      - external
    volumes:
      - beszel_data:/beszel_data


  # NGinx reverse proxy
  nginx:
    image: nginx:alpine

    depends_on:
      - apex
      - blog
      - openwebui
      - beszel
      - vouch

    ports:
      - 443:443
    networks:
      - internal
      - external

    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./nginx/snippets/:/etc/nginx/snippets/:ro
      - ./nginx/favicons/:/favicons/:ro

      - /etc/letsencrypt/live/skoh.dev/fullchain.pem:/etc/ssl/skoh-dev/fullchain.pem:ro
      - /etc/letsencrypt/live/skoh.dev/privkey.pem:/etc/ssl/skoh-dev/privkey.pem:ro


networks:
  internal:
    internal: true
  external:

volumes:
  beszel_data:
  open-webui:
