services:

  # NextJS webserver
  apex:
    build:
      context: ./apex
    networks:
        - internal

  # Open WebUI
  openwebui:
    image: ghcr.io/open-webui/open-webui:0.6.33

    networks:
      - external
    volumes:
      - open-webui:/app/backend/data
    # environment:
    #   WEBUI_AUTH: False

  # Beszel
  beszel:
    image: henrygd/beszel:0.13.1
    container_name: beszel
    restart: unless-stopped

    networks:
      - external
    volumes:
      - beszel_data:/beszel_data


  # NGinx reverse proxy
  nginx:
    image: nginx:alpine

    depends_on:
      - apex
      - openwebui
      - beszel

    ports:
      - 80:80
      - 443:443
    networks:
        - internal
        - external

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/favicons/:/favicons/:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro

      - /etc/letsencrypt/live/skoh.dev/fullchain.pem:/etc/ssl/skoh-dev/fullchain.pem:ro
      - /etc/letsencrypt/live/skoh.dev/privkey.pem:/etc/ssl/skoh-dev/privkey.pem:ro



networks:
  internal:
    internal: true
  external:

volumes:
  beszel_data:
  open-webui:
