services:
  apex:
    build:
      context: ./apex
    ports:
      - "5000:5000"

  api:
    build:
      context: ./api
    ports:
      - "5001:5001"

  old-go:
    build:
      context: ./_archive/old-go
    ports:
      - "5500:5500"
  
  nginx:
    build:
      context: ./
    ports:
      - "443:443"
    depends_on:
      - apex
      - api
      - old-go
