services:

  # NextJS webserver
  apex:
    build:
      context: ./apex
    networks:
        - internal

  # Blog
  blog:
    build:
      context: ./blog
    networks:
      - internal
    ports:
      - 8000:80

  # Beszel
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped

    networks:
      - external
    volumes:
      - beszel_data:/beszel_data


  # NGinx reverse proxy
  nginx:
    image: nginx:alpine

    depends_on:
      - apex
      - blog
      - beszel

    ports:
      - 443:443
    networks:
      - internal
      - external
      - odysseus_default

    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./nginx/snippets/:/etc/nginx/snippets/:ro
      - ./nginx/favicons/:/favicons/:ro

      - /etc/letsencrypt/live/skoh.dev/fullchain.pem:/etc/ssl/skoh-dev/fullchain.pem:ro
      - /etc/letsencrypt/live/skoh.dev/privkey.pem:/etc/ssl/skoh-dev/privkey.pem:ro



networks:
  internal:
    internal: true
  odysseus_default:
    external: true
  external:

volumes:
  beszel_data:
  open-webui:
