worker_processes 1;
events {
  worker_connections 1024;
}


http {

  # Redirect http to https
  server {
    listen 80;
    server_name _;
    return 301 https://$host$request_uri;
  }
  

  # skoh.dev
  server {
    listen 443 ssl;
    server_name skoh.dev;

    ssl_certificate /etc/nginx/ssl/domain.cert.pem;
    ssl_certificate_key /etc/nginx/ssl/private.key.pem;
    ssl_trusted_certificate /etc/nginx/ssl/intermediate.cert.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384';

    location / {
      proxy_pass http://skoh.dev:5000/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # redirect links
    location = /ln/ytb { return 301 https://youtube.com/@Skoh; }
    location = /ln/youtube { return 301 https://youtube.com/@Skoh; }
    location = /ln/gh { return 301 https://github.com/SkohTV; }
    location = /ln/github { return 301 https://github.com/SkohTV; }
    location = /ln/discord { return 301 https://discord.com/invite/G8hrncZ; }
  }


  # api.skoh.dev
  server {
    listen 443 ssl;
    server_name api.skoh.dev;

    ssl_certificate /etc/nginx/ssl/domain.cert.pem;
    ssl_certificate_key /etc/nginx/ssl/private.key.pem;
    ssl_trusted_certificate /etc/nginx/ssl/intermediate.cert.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384';

    location / {
      proxy_pass http://skoh.dev:5001/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }

}
