# Locations
ServerName localhost
ServerAdmin root@localhost
ServerRoot /etc/apache2

# Seems important
Mutex file:${APACHE_LOCK_DIR} default
PidFile ${APACHE_PID_FILE}

ServerTokens Prod
UseCanonicalName On
TraceEnable Off
HostnameLookups Off


# Anti DDOS ?
Timeout 300

MaxRequestWorkers 100

KeepAlive On
MaxKeepAliveRequests 100
KeepAliveTimeout 5


# These need to be set in /etc/apache2/envvars
User ${APACHE_RUN_USER}
Group ${APACHE_RUN_GROUP}


# Include module configuration:
IncludeOptional mods-enabled/*.load
IncludeOptional mods-enabled/*.conf

IncludeOptional conf-enabled/*.conf
IncludeOptional sites-enabled/*.conf

# Include ports.conf
Listen 5002


# Which files are allowed to be looked at
<Directory />
  Options FollowSymLinks
  AllowOverride None
  Require all denied
</Directory>

<Directory /usr/share>
  AllowOverride None
  Require all granted
</Directory>


# Check for htaccess in directories
AccessFileName .htaccess

# Hide htaccess and htpasswd to clients
<FilesMatch "^\.ht">
  Require all denied
</FilesMatch>


# Logging
ErrorLog ${APACHE_LOG_DIR}/error.log
LogLevel debug

LogFormat "%v:%p %h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" vhost_combined
LogFormat "%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined
LogFormat "%h %l %u %t \"%r\" %>s %O" common
LogFormat "%{Referer}i -> %U" referer
LogFormat "%{User-agent}i" agent
