location = /validate {
    internal;
    proxy_pass http://vouch:9090/validate;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Cookie $http_cookie;
    proxy_set_header X-Vouch-Requested-URL $scheme://$host$request_uri;

    proxy_pass_request_body off;
    proxy_set_header Content-Length "";
}

location @error401 {
    return 302 https://vouch.skoh.dev/login?url=$scheme://$host$request_uri;
}
